### ISSUE TITLE
Plugin imports wrong file when multiple resource or library files have the same name in different directories

### ISSUE THREAD

**Issue by awesomeunleashed** [lte2000/intellibot#8] opened 2020-03-24 18:08 UTC
Thanks for working on this plugin, it addresses most of the issues we had in the base plugin.

We have found, however, that when importing a local library or resource file, if there are multiple files named the same in the project (in different folders), the plugin always imports the first one instead of the one specified by the relative path (which robot will import when actually running the tests). 

[Here is a simple project](https://github.com/lte2000/intellibot/files/4376916/intellibot-test.zip) that demonstrates this behavior. In `module2/test.robot` in the editor, it can't find the keywords used in the test case, because it is importing `module1/keywords.robot` and `module1/Util.py`. However, when the tests are run, robot correctly imports `module2/keywords.robot` and `module2/Util.py`.

Any chance this could be addressed? I could look into it myself if you don't have the capacity, but I haven't done any JetBrains plugin development before, so I would need to be pointed to where in the project to look.

**Comment by lte2000** [comment] 2020-03-25 14:50
You can try: Close all files, restart PyCharm. Then if you open module2/tests.robot first, it will import module2/keywords.robot. Howerver, you open module1/test.robot later, it will also import module2/keywords.robot. 

That means, if resource/library have same name, the first loaded one will always be used by the plugin.

The issue is caused by that the cache it used is based on the resource/library name only.
You can resolve it by improve the function findRobot and findPython in com/millennialmedia/intellibot/psi/ref/RobotFileManager.java
Thanks!

**Comment by lte2000** [comment] 2021-08-21 04:31
@awesomeunleashed  please try https://github.com/lte2000/intellibot/raw/c697374f8b00a0f1fd0d25f70c7bb36c9fa78661/intellibot.jar
It now resolve related library/resource path before cache.

**Comment by awesomeunleashed** [comment] 2021-08-21 16:52
> @awesomeunleashed please try https://github.com/lte2000/intellibot/raw/c697374f8b00a0f1fd0d25f70c7bb36c9fa78661/intellibot.jar
> It now resolve relative library/resource path before cache.

I'm not on a team that uses PyCharm or Robot Framework anymore, so unfortunately I can't test it, but I appreciate you working on this! I'll be sure to try it out if I ever start using that stack again.

**Comment by lte2000** [comment] 2021-08-29 13:34
fixed in [v0.10.143.398](https://plugins.jetbrains.com/plugin/17424-intellibot-patched/versions/stable/134225)

**Closed by lte2000** 2021-08-29 13:34 UTC
Labels: bug
